test0: mart_test0.c
	gcc -o mart_test0 mart_test0.c -I/usr/opencv/OpenCV-2.1.0/include/ -L/usr/opencv/OpenCV-2.1.0/release/lib/ -lm -lcxcore -lcv -lcvaux -lhighgui -lml

sgbm: sgbm.cpp
	g++ -o sgbm sgbm.cpp -I/usr/opencv/OpenCV-2.1.0/include/ -L/usr/opencv/OpenCV-2.1.0/release/lib/ -lm -lcxcore -lcv -lcvaux -lhighgui -lml
