chesstest: chessboard_test.cpp
	g++ -o chessboard_test chessboard_test.cpp -I /home/moos/prog/opencv/OpenCV-2.1.0/include/opencv/ -L /home/moos/prog/opencv/OpenCV-2.1.0/lib/ -lcxcore -lcv -lhighgui

sgbm: sgbm.cpp
	g++ -o sgbm sgbm.cpp -I/usr/opencv/OpenCV-2.1.0/include/ -L/usr/opencv/OpenCV-2.1.0/release/lib/ -lm -lcxcore -lcv -lcvaux -lhighgui -lml
